#!/bin/bash
cp -R src/swagger/ lib/src/swagger/
rm lib/src/swagger/index.ts
mkdir -p lib/public
cp -R coverage/ lib/public/coverage/
cp -R src/infrastructure/repository/prisma-client lib/src/infrastructure/repository/prisma-client