
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.18.0
 * Query Engine version: 34b5a692b7bd79939a9a2c3ef97d816e749cda2f
 */
Prisma.prismaVersion = {
  client: "6.18.0",
  engine: "34b5a692b7bd79939a9a2c3ef97d816e749cda2f"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.DailyStatsScalarFieldEnum = {
  id: 'id',
  date: 'date',
  totalSchools: 'totalSchools',
  newSchools: 'newSchools',
  activeSchools: 'activeSchools',
  schoolGrowth: 'schoolGrowth',
  totalPrograms: 'totalPrograms',
  newPrograms: 'newPrograms',
  activePrograms: 'activePrograms',
  programGrowth: 'programGrowth',
  totalFaqs: 'totalFaqs',
  newFaqs: 'newFaqs',
  faqGrowth: 'faqGrowth',
  totalInquiries: 'totalInquiries',
  newInquiries: 'newInquiries',
  inquiryGrowth: 'inquiryGrowth',
  totalAdmins: 'totalAdmins',
  newAdmins: 'newAdmins',
  activeAdmins: 'activeAdmins',
  adminGrowth: 'adminGrowth',
  totalPosts: 'totalPosts',
  publishedPosts: 'publishedPosts',
  scheduledPosts: 'scheduledPosts',
  draftPosts: 'draftPosts',
  newPosts: 'newPosts',
  postGrowth: 'postGrowth',
  unpublishedPosts: 'unpublishedPosts',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TokenScalarFieldEnum = {
  id: 'id',
  tokenId: 'tokenId',
  token: 'token',
  type: 'type',
  expiresIn: 'expiresIn',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AdminScalarFieldEnum = {
  id: 'id',
  adminId: 'adminId',
  email: 'email',
  firstName: 'firstName',
  lastName: 'lastName',
  middleName: 'middleName',
  gender: 'gender',
  accountSuspended: 'accountSuspended',
  nationality: 'nationality',
  countryOfResidence: 'countryOfResidence',
  about: 'about',
  primaryImage: 'primaryImage',
  secondaryImage: 'secondaryImage',
  socials: 'socials',
  phoneNumber: 'phoneNumber',
  jobTitle: 'jobTitle',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DepartmentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  leadId: 'leadId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  leadId: 'leadId',
  departmentId: 'departmentId',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FaqScalarFieldEnum = {
  id: 'id',
  question: 'question',
  answer: 'answer',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InquiryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  phoneNumber: 'phoneNumber',
  email: 'email',
  message: 'message',
  subject: 'subject',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ActivityLogScalarFieldEnum = {
  id: 'id',
  adminId: 'adminId',
  resource: 'resource',
  resourceId: 'resourceId',
  action: 'action',
  message: 'message',
  previousState: 'previousState',
  currentState: 'currentState',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SchoolScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  logo: 'logo',
  schoolImage: 'schoolImage',
  name: 'name',
  slug: 'slug',
  state: 'state',
  country: 'country',
  city: 'city',
  address: 'address',
  link: 'link',
  institutionType: 'institutionType',
  ownershipType: 'ownershipType',
  currency: 'currency',
  overview: 'overview',
  active: 'active',
  randomKey: 'randomKey',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccommodationScalarFieldEnum = {
  id: 'id',
  description: 'description',
  schoolId: 'schoolId',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProgramScalarFieldEnum = {
  id: 'id',
  programId: 'programId',
  schoolId: 'schoolId',
  randomKey: 'randomKey',
  name: 'name',
  slug: 'slug',
  faculty: 'faculty',
  degreeType: 'degreeType',
  overview: 'overview',
  description: 'description',
  requirements: 'requirements',
  financialAids: 'financialAids',
  applicationFee: 'applicationFee',
  applicationFeeDiscount: 'applicationFeeDiscount',
  tuitionFee: 'tuitionFee',
  tuitionFeeType: 'tuitionFeeType',
  timeframe: 'timeframe',
  duration: 'duration',
  minimumEducationLevel: 'minimumEducationLevel',
  minimumEducationDegree: 'minimumEducationDegree',
  minimumEligibilityGpa: 'minimumEligibilityGpa',
  pgwp: 'pgwp',
  active: 'active',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EnglishProficiencyScalarFieldEnum = {
  test: 'test',
  score: 'score',
  programId: 'programId'
};

exports.Prisma.IntakeScalarFieldEnum = {
  id: 'id',
  intake: 'intake',
  startDate: 'startDate',
  deadline: 'deadline',
  status: 'status',
  schoolId: 'schoolId',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BlogPostScalarFieldEnum = {
  id: 'id',
  blogPostId: 'blogPostId',
  title: 'title',
  slug: 'slug',
  excerpt: 'excerpt',
  content: 'content',
  coverImage: 'coverImage',
  featured: 'featured',
  status: 'status',
  publishedAt: 'publishedAt',
  authorId: 'authorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TagScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ScholarshipScalarFieldEnum = {
  id: 'id',
  scholarshipId: 'scholarshipId',
  title: 'title',
  slug: 'slug',
  subtitle: 'subtitle',
  banner: 'banner',
  overview: 'overview',
  description: 'description',
  category: 'category',
  featured: 'featured',
  eligibilityRequirements: 'eligibilityRequirements',
  active: 'active',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FinancialAidScalarFieldEnum = {
  id: 'id',
  financialAidId: 'financialAidId',
  citizenship: 'citizenship',
  canadianResident: 'canadianResident',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  phoneNumber: 'phoneNumber',
  schoolSlug: 'schoolSlug',
  programSlug: 'programSlug',
  studyLevel: 'studyLevel',
  pgwp: 'pgwp',
  hasOfferLetter: 'hasOfferLetter',
  loanType: 'loanType',
  livingExpensesCoverage: 'livingExpensesCoverage',
  programStarted: 'programStarted',
  gpa: 'gpa',
  nextSchoolTerm: 'nextSchoolTerm',
  partner: 'partner',
  proofOfAddress: 'proofOfAddress',
  identification: 'identification',
  resume: 'resume',
  transcript: 'transcript',
  bankStatement: 'bankStatement',
  immigrationDocument: 'immigrationDocument',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  programId: 'programId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.TokenOrderByRelevanceFieldEnum = {
  tokenId: 'tokenId',
  token: 'token'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.AdminOrderByRelevanceFieldEnum = {
  adminId: 'adminId',
  email: 'email',
  firstName: 'firstName',
  lastName: 'lastName',
  middleName: 'middleName',
  nationality: 'nationality',
  countryOfResidence: 'countryOfResidence',
  about: 'about',
  jobTitle: 'jobTitle',
  createdById: 'createdById'
};

exports.Prisma.DepartmentOrderByRelevanceFieldEnum = {
  leadId: 'leadId'
};

exports.Prisma.TeamOrderByRelevanceFieldEnum = {
  name: 'name',
  leadId: 'leadId',
  createdById: 'createdById'
};

exports.Prisma.FaqOrderByRelevanceFieldEnum = {
  question: 'question',
  answer: 'answer',
  createdById: 'createdById'
};

exports.Prisma.InquiryOrderByRelevanceFieldEnum = {
  name: 'name',
  email: 'email',
  message: 'message',
  subject: 'subject'
};

exports.Prisma.ActivityLogOrderByRelevanceFieldEnum = {
  resource: 'resource',
  action: 'action',
  message: 'message'
};

exports.Prisma.SchoolOrderByRelevanceFieldEnum = {
  schoolId: 'schoolId',
  name: 'name',
  slug: 'slug',
  state: 'state',
  country: 'country',
  city: 'city',
  address: 'address',
  link: 'link',
  overview: 'overview',
  createdById: 'createdById'
};

exports.Prisma.AccommodationOrderByRelevanceFieldEnum = {
  description: 'description',
  schoolId: 'schoolId',
  createdById: 'createdById'
};

exports.Prisma.ProgramOrderByRelevanceFieldEnum = {
  programId: 'programId',
  schoolId: 'schoolId',
  name: 'name',
  slug: 'slug',
  faculty: 'faculty',
  degreeType: 'degreeType',
  overview: 'overview',
  description: 'description',
  requirements: 'requirements',
  financialAids: 'financialAids',
  minimumEducationLevel: 'minimumEducationLevel',
  createdById: 'createdById'
};

exports.Prisma.EnglishProficiencyOrderByRelevanceFieldEnum = {
  test: 'test',
  programId: 'programId'
};

exports.Prisma.IntakeOrderByRelevanceFieldEnum = {
  intake: 'intake',
  schoolId: 'schoolId',
  createdById: 'createdById'
};

exports.Prisma.BlogPostOrderByRelevanceFieldEnum = {
  blogPostId: 'blogPostId',
  title: 'title',
  slug: 'slug',
  excerpt: 'excerpt',
  content: 'content',
  authorId: 'authorId'
};

exports.Prisma.TagOrderByRelevanceFieldEnum = {
  name: 'name',
  createdById: 'createdById'
};

exports.Prisma.CategoryOrderByRelevanceFieldEnum = {
  name: 'name',
  createdById: 'createdById'
};

exports.Prisma.ScholarshipOrderByRelevanceFieldEnum = {
  scholarshipId: 'scholarshipId',
  title: 'title',
  slug: 'slug',
  subtitle: 'subtitle',
  overview: 'overview',
  description: 'description',
  category: 'category',
  eligibilityRequirements: 'eligibilityRequirements',
  createdById: 'createdById'
};

exports.Prisma.FinancialAidOrderByRelevanceFieldEnum = {
  financialAidId: 'financialAidId',
  citizenship: 'citizenship',
  canadianResident: 'canadianResident',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  schoolSlug: 'schoolSlug',
  programSlug: 'programSlug',
  studyLevel: 'studyLevel',
  pgwp: 'pgwp',
  hasOfferLetter: 'hasOfferLetter',
  loanType: 'loanType',
  livingExpensesCoverage: 'livingExpensesCoverage',
  programStarted: 'programStarted',
  partner: 'partner',
  programId: 'programId'
};
exports.TokenType = exports.$Enums.TokenType = {
  verify: 'verify',
  reset: 'reset'
};

exports.Gender = exports.$Enums.Gender = {
  Male: 'Male',
  Female: 'Female',
  Others: 'Others'
};

exports.DepartmentName = exports.$Enums.DepartmentName = {
  Executive: 'Executive',
  Marketing: 'Marketing',
  Admissions: 'Admissions',
  Communications: 'Communications',
  Technical: 'Technical',
  Human_Resource: 'Human_Resource',
  Quality_Assurance: 'Quality_Assurance'
};

exports.InstitutionType = exports.$Enums.InstitutionType = {
  university: 'university',
  college: 'college'
};

exports.OwnershipType = exports.$Enums.OwnershipType = {
  private: 'private',
  public: 'public'
};

exports.Currency = exports.$Enums.Currency = {
  USD: 'USD',
  CAD: 'CAD',
  AUD: 'AUD',
  NGN: 'NGN',
  EUR: 'EUR',
  GBP: 'GBP'
};

exports.TuitionFeeType = exports.$Enums.TuitionFeeType = {
  per_year: 'per_year',
  per_semester: 'per_semester',
  full: 'full'
};

exports.Timeframe = exports.$Enums.Timeframe = {
  day: 'day',
  week: 'week',
  month: 'month',
  year: 'year'
};

exports.IntakeStatus = exports.$Enums.IntakeStatus = {
  open: 'open',
  closed: 'closed',
  likely_open: 'likely_open'
};

exports.BlogStatus = exports.$Enums.BlogStatus = {
  draft: 'draft',
  scheduled: 'scheduled',
  published: 'published',
  unpublished: 'unpublished'
};

exports.Prisma.ModelName = {
  DailyStats: 'DailyStats',
  Token: 'Token',
  Admin: 'Admin',
  Department: 'Department',
  Team: 'Team',
  Faq: 'Faq',
  Inquiry: 'Inquiry',
  ActivityLog: 'ActivityLog',
  School: 'School',
  Accommodation: 'Accommodation',
  Program: 'Program',
  EnglishProficiency: 'EnglishProficiency',
  Intake: 'Intake',
  BlogPost: 'BlogPost',
  Tag: 'Tag',
  Category: 'Category',
  Scholarship: 'Scholarship',
  FinancialAid: 'FinancialAid'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
